#!/bin/bash -login
#PBS -l walltime=24:00:00,nodes=1:ppn=4
#PBS -l mem=3GB
#PBS -l feature='intel16|intel14'
#PBS -l file=2GB
#PBS -j oe
#PBS -N soursigs
#PBS -W umask=027
#PBS -o ${PBS_O_WORKDIR}/logs/45/${PBS_JOBID}
#PBS -t 1-39

cd $PBS_O_WORKDIR

source modules.hpcc
source iam/soursigs_sqs

set -o nounset
set -o errexit
set -x

celery -A soursigs -c 16 -l INFO worker & export CELERY_PID=$!

sleep 86340  # sleep for 23h59m, send TERM signal to soft-stop worker

kill -TERM $CELERY_PID

cat ${PBS_NODEFILE}       # Output Contents of the PBS NODEFILE

env | grep PBS            # Print out values of the current jobs PBS environment variables

qstat -f ${PBS_JOBID}     # Print out final statistics about resource uses before job exits
